FROM python:3.12-slim

WORKDIR /opt/app

RUN apt-get update && apt-get install -y \
    openjdk-21-jre \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry

COPY python/etl ./etl
COPY python/shared ./shared

WORKDIR /opt/app/etl

RUN poetry config virtualenvs.create false \
 && poetry install --no-interaction --no-cache

# CMD ["python", "-m", "etl.end_to_end_etl"]

CMD ["tail", "-f", "/dev/null"]