from shared.config.to_postgres.classes import TableConfig


TABLE_CONFIGS = [
    TableConfig(
        id="j211__MM_SAP_DS_MARA",
        source_system="J211",
        source_database="T1_MasterData",
        source_table="MM_SAP_DS_MARA",
        target_table="MARA",
        keys=["MANDT", "MATNR"],
        where_clause=None,
        cadence="daily",
        dataset="materials",
    ),
    TableConfig(
        id="j211__MM_SAP_DS_MVKE",
        source_system="J211",
        source_database="T1_MasterData",
        source_table="MM_SAP_DS_MVKE",
        target_table="MVKE",
        keys=["MANDT", "MATNR"],
        where_clause=None,
        cadence="daily",
        dataset="materials",
    ),
    TableConfig(
        id="j211__MM_SAP_DS_MARC",
        source_system="J211",
        source_database="T1_MasterData",
        source_table="MM_SAP_DS_MARC",
        target_table="MARC",
        keys=["MANDT", "MATNR", "WERKS"],
        where_clause=None,
        cadence="daily",
        dataset="materials",
    ),
    TableConfig(
        id="j211__SD_SAP_DS_VBAK",
        source_system="J211",
        source_database="T1_Trans_FB",
        source_table="dbo.SD_SAP_DS_VBAK",
        target_table="VBAK",
        keys=["VBELN"],
        where_clause=None,
        cadence="fast",
        dataset="sales_orders",
    ),
    TableConfig(
        id="j211__SD_SAP_DS_VBAP",
        source_system="J211",
        source_database="T1_Trans_FB",
        source_table="dbo.SD_SAP_DS_VBAP",
        target_table="VBAP",
        keys=["MANDT", "VBELN", "POSNR"],
        where_clause=None,
        cadence="fast",
        dataset="sales_orders",
    ),
    TableConfig(
        id="j211__J8329_OTIF_History",
        source_system="J211",
        source_database="T3_OTIF",
        source_table="J8329_OTIF_History",
        target_table="otif_historic",
        keys=["SO", "SOI"],
        where_clause=None,
        cadence="daily",
        dataset="otif",
    ),
    TableConfig(
        id="j211__J8391_Backorders_v2_Historic",
        source_system="J211",
        source_database="T3_OTIF",
        source_table="J8391_Backorders_v2_Historic",
        target_table="backorders_historic",
        keys=["SO", "SOI", "InsertedDate"],
        where_clause=None,
        cadence="daily",
        dataset="otif",
    ),
    TableConfig(
        id="j211__temp_gp_load_test",
        source_system="J211",
        source_database="T3_OTIF",
        source_table="temp_gp_load_test",
        target_table="temp_gp_load_test",
        keys=["ID"],
        where_clause=None,
        cadence="fast",
        dataset="test",
    ),
]
